[package]
name = "noty"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = "0.1"
leptos_router = "0.1"
pulldown-cmark = "0.9" # For Markdown support
serde = { version = "1.0", features = [
    "derive",
] } # For serializing the seed phrase
anyhow = "1.0" # Error handling
